parent: "configs/base.yaml"

save_path: "output/replica_test/debug"

# map params
uniform_sample_num: 46080
min_depth: 0.3
max_depth: 2.5
KNN_num: 20
KNN_threshold: -1
memory_length: 3
global_keyframe_num: 3

# map preprocess
invalid_confidence_thresh: 0.1

# dataset params:
type: "Ours"
source_path: "data/Ours/hotel"

# state manage
stable_confidence_thres: 250
unstable_time_window: 400

# optimize params:
gaussian_update_iter: 50
gaussian_update_frame: 8
position_lr : 0.001
feature_lr : 0.001
opacity_lr : 0.000
scaling_lr : 0.002
rotation_lr : 0.001
KNN_threshold: -1

# track params
use_orb_backend: True
tracker_max_fps: 15
orb_settings_path: "configs/orb_config/ours.yaml"

use_gt_pose: False
icp_use_model_depth: True # if False, use dataset depth frame to frame
icp_matches_threshold: 0.2 # ratio * valie pixels
icp_normal_threshold: 20 # degree
icp_sample_distance_threshold: 0.01 # m
icp_sample_normal_threshold: 0.01 # cos similarity
icp_warmup_frames: 200
icp_fail_threshold: 0.01